### PR TITLE
Upgrade to Angular 11

### LINKED ISSUE #237: Update Angular version to 11.2.14
**Is your feature request related to a problem? Please describe.**
Angular version is 10.2.5, it is very outdated.

**Describe the solution you'd like**
Update of angular version and relevant dependencies including node version supporting angular 11.2.14.

### PR DESCRIPTION
**Pull request by MadLamprey**
### Summary:

This pull request addresses some outdated packages in our application.

Fixes #237

### Changes Made:

<ul>
<li> Upgrade to Angular 11 using `ng update` 
<ul>
<li>See: <a href='https://update.angular.io/?l=3&v=10.2-11.0'>https://update.angular.io/?l=3&v=10.2-11.0</a>
<li>All changes mentioned have been reviewed
<li>Dependencies that have been updated, other than those mentioned in the list, include:
<ul>
<li>apollo-angular
<li>@angular-devkit/build-angular
</ul> </ul> </ul>

### Proposed Commit Message:

```
Upgrade to Angular 11

Some of our packages are old and outdated. We should actively maintain 
and keep these packages up-to-date so it is easier to maintain in the 
future.

Let's upgrade to Angular 11 to keep our packages up-to-date.
```

### CODE REVIEW

**Comment by chunweii** [comment]
There is a build error, please check and fix it @MadLamprey. Thank you

**Comment by Arif-Khalid** [comment]
I have tested the changes and all current functionality is working as intended. LGTM!

**Comment by gycgabriel** [comment]
Version upgrades need to tested on multiple platforms similar to https://github.com/CATcher-org/CATcher/pull/1242

**Review by cheehongw — COMMENTED** [review]
## System
**OS**: Windows 10 22H2
**Browser**: Chrome
**Browser Version**: Version 121.0.6167.185 (Official Build) (64-bit)
**Local Angular Version**: 11.2.14
**Node Version**: 14.21.2
**npm version**: 6.14.17

## Actions Run
`npm install`: success 
`npm run ng:serve:web`

## Tested Features
Switching between repositories
Filtering by labels


No bugs found

**Comment by vigneshsankariyer1234567890** [comment]
macOS works too :)
### System
OS: macOS 13.3.1 (Ventura)
Browser: Chrome arm64
Browser Version: Version 120.0.6099.199 (Official Build) (arm-64)
Local Angular Version: 11.2.14
Node Version: 14.21.2
npm version: 6.14.17

### Actions Run
npm install: success
npm run ng:serve:web

### Tested Features
Switching between repositories
Filtering by labels

No bugs found

**Comment by Arif-Khalid** [comment]
System
OS: Windows 11 23H2
Browser: Opera GX
Browser Version: LVL5 (core: 106.0.4998.76)
Local Angular Version: 11.2.14
Node Version: 16.10.0
npm version: 7.5.6

Actions Run
npm install: success
npm run ng:serve:web

Tested Features
Switching between repositories
Filtering by labels

No bugs found

**Comment by Arif-Khalid** [comment]
### System
OS: Windows 11 23H2
Browser: Chrome
Browser Version: 121.0.6167.185 (Official Build) (64-bit)
Local Angular Version: 11.2.14
Node Version: 16.10.0
npm version: 7.5.6

### Actions Run
npm install: success
npm run ng:serve:web

### Tested Features
Switching between repositories
Filtering by labels

No bugs found

**Review by cheehongw — APPROVED** [review]
LGTM

**Pull request merged**
