### PR TITLE
Show list of hidden users

### LINKED ISSUE #225: Show a list of hidden users at the end
**Describe the solution you'd like**
After #192 is merged, possible to accumulate a list of users that were hidden at the end.

### PR DESCRIPTION
**Pull request by nknguyenhc**
### Summary:

Fixes #225

#### Type of change:

- ✨ New Feature/ Enhancement

### Changes Made:

* Add a new component to display the list of hidden users.
* Add event emitter from card components to update issue count.

### Screenshots:

image

### Proposed Commit Message:

```
Add column of hidden users

After #192, assignees of a repo without any issues or PRs
are hidden. Now, add the column to display such users
with 0 PRs and issues.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [X] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [X] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

**Review by cheehongw — COMMENTED** [review]
The code is working and is nice to read.

Just a nitpick on the styling
image

Also, leaving this PR open for any comments on the UI/UX 
@CATcher-org/2324s2

**Review by gycgabriel — CHANGES_REQUESTED** [review]
Thanks for the PR

UI can be improved, I would suggest some left padding in between image and username, overflow if its too long like vignesh' 
image


image

Better to make it as similar to the columns on the left

Try reducing height, vertical padding/margins, it'll look more rectangular and nicer and use vertical space better

**Comment by nknguyenhc** [comment]
I have updated the stylesheets! Let me know if there are any other issues.

**Review by gycgabriel — CHANGES_REQUESTED** [review]
image

Have a mat card title to make it look like the left header, plus points if you can mimic the number count

If possible, it would be better for the font of the user on the right to be equal or smaller than the issue title on the left, so that it doesn't draw so much attention instead of the issues

**Comment by nknguyenhc** [comment]
I have:

* Added the count of hidden users.
* Wrap the header text around a `mat-card-title`.
* Reduce font-size and avatar size of hidden users.

Do let me know if there are any other issues!

image

**Review by gycgabriel — APPROVED** [review]
LGTM

**Pull request merged**
