### PR TITLE
[#72] Remove code related to creating and updating repos

### LINKED ISSUE #72: Remove unused code from CATcher
Since WATcher is a fork from CATcher, there are still many instances of old and unused code from CATcher. Let's remove these codes.

- `DataService` (used to access data.csv in CATcher)
- `src/app/core/services/session-fix-confirmation` (component to ask user for permission to create a new repository)
- `fetchSettingsFile()` and `fetchDataFile()` in `github.service.ts`
- All tests related to the above

There could be more unused code in the project. These are some that I have found

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
### Summary:
fixes part related to creating/updating repos in #72 

### Changes Made:
- Removes code related to creating and modifying content on GitHub
- Removes unused filters

### Commit Message:

```
As a majority of the WATcher code base is ported over from CATcher,
it includes a lot of unused code. One such area is the code related to 
creating and updating issues on GitHub. Since WATcher is mainly used
to read data from GitHub and not modify data for now. 

Let's remove code that is related to modifying or creating repos
```

### CODE REVIEW

**Review by chunweii — CHANGES_REQUESTED** [review]
In github.service.ts, the following variables/functions are not in use:

- `MOD_ORG`, `DATA_REPO`, `fetchSettingsFile()`
- `GithubService.`: `storeOrganizationDetails()`, `createRepository()`, `areUsersAssignable()`, `closeIssue()`, `updateIssue()`, `fetchDataFile() // linked to data.service.ts`, `fetchSettingsFile()`

Since this is a rather large change, it will be good to have another developer to review this

**Review by gycgabriel — APPROVED** [review]
LGTM

**Comment by gycgabriel** [comment]
I noticed chunwei's comment, you can decide if it's in the scope of your PR and update. Otherwise I think its lgtm

**Comment by Eclipse-Dominator** [comment]
> I noticed chunwei's comment, you can decide if it's in the scope of your PR and update. Otherwise I think its lgtm

I have removed `createRepository()`, `updateIssue()`, `closeIssue()` as these functions relates more towards modifying repository which aligns with the goal of this PR.

**Review by gycgabriel — APPROVED** [review]
LGTM

**Comment by gycgabriel** [comment]
@chunweii require your approval to pass

**Review by chunweii — APPROVED** [review]
LGTM

**Pull request merged**
