### PR TITLE
68 upgrade angular to v10 and node to v14

### LINKED ISSUE #68: Angular Upgrade
Similar to CATcher, let's try to upgrade to at least v10+

### PR DESCRIPTION
**Pull request by Echomo-Xinyu**
### Summary:

Fixes #68 

### Changes Made:

- Upgrade Angular version from v9.1 to v10.2
- Remove outdated parameters for MarkedOptions in ngx-markdown
- Use LTS version Node v14 instead of Node v12

### Commit Message:

```
Let's upgrade Angular version to v10.2 and use Node v14 instead of v12
```

### CODE REVIEW

**Comment by chunweii** [comment]
We can consider updating the node version to 14 to be consistent with CATcher. The current version is 12, according to the github workflow files.

**Comment by Echomo-Xinyu** [comment]
> We can consider updating the node version to 14 to be consistent with CATcher. The current version is 12, according to the github workflow files.

Done!

**Comment by chunweii** [comment]
Tested and working on:

OS: Windows 11 22H2
Browser: Google Chrome
Browser Version: Version 111.0.5563.147 (Official Build) (64-bit)

OS: Windows 11 22H2
Browser: Firefox
Browser Version: Version 111.0.1 (64-bit)

**Review by chunweii — APPROVED** [review]

**Comment by kkangs0226** [comment]
Let's merge this PR after #104 since #104 was made first!

**Pull request merged**
