### PR TITLE
Refactor Phase Service and remove Phase

### LINKED ISSUE #276: Refactor PhaseService and remove Phase
`PhaseService` is a service carried over from CATcher when WATcher was created. However, WATcher has no concept of phases, but the dashboard selector makes use of this. Let's refactor `PhaseService` so that the codebase is clearer and friendlier

### PR DESCRIPTION
**Pull request by NereusWB922**
### Summary:

Fixes #276 

#### Type of change:

- 🎨 Code Refactoring

### Changes Made:

- Rename phase to view

### Proposed Commit Message:

```
Replace Phase with View

The concept of "Phase" is inherited from CATcher. Instead of "Phase", 
WATcher provides different "Views" of contributions in a repository.

Let's replace "Phase" with "View".
```

### CODE REVIEW

**Review by nknguyenhc — COMMENTED** [review]
image

A quick search on the usage of "phase" word in the repo shows these usages (excluding test files). Can you investigate if these usages can be removed as well?

**Review by nknguyenhc — DISMISSED** [review]
Sure, we can remove that in a separate PR. Other than that, LGTM!

**Review by luminousleek — APPROVED** [review]
LGTM! Thanks for the comprehensive work. Your PR on the activity dashboard URL needs to be refactored after this is merged though.

**Comment by NereusWB922** [comment]
Thanks for the review. I will resolve the conflicts for that pr after merging this.

**Pull request merged**
