### PR TITLE
Implement filter for Task Owners

### LINKED ISSUE #342: Add filter for assignee
**Is your feature request related to a problem? Please describe.**
Currently, we can group issues and PRs by different criteria, not only by assignee. We should provide a filter for the assignee so users can filter the issue based on the assignee in different groupings.

### PR DESCRIPTION
**Pull request by kokerinks**
### Summary:

In this context, we define a **Task owner** as follows:
- For an **issue**, task owner refers to the **members assigned** that issue
- For a **pull request**, task owner refers to the **author/creator** of the PR

Fixes #342 

#### Type of change:

- ✨ New Feature/ Enhancement

### Changes Made:

- Implemented a new filter which filters issues/PRs based on a Task Owner, i.e.:
  - Author/creator for PRs
  - Assignees for issues

### Screenshots:

image

### Proposed Commit Message:

```
Implement filter for Task Owners

Having a function to filter issues/PRs by task owners can 
give users a more organised overview of the contributions
made by each member in the project. 

Hence, let's add it to the list of existing filters we have 
currently for users.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [X] I have tested my changes thoroughly.
- [X] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [X] I have added or modified code comments to improve code readability where necessary.
- [X] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

**Review by NereusWB922 — COMMENTED** [review]
Hi, just one minor comment. Other than that, everything look good.

**Review by NereusWB922 — APPROVED** [review]
LGTM

**Comment by NereusWB922** [comment]
@kokerinks Approved. You can merge it when you are ready

**Comment by kokerinks** [comment]
@NereusWB922 can you help to merge this please? I dont have enough write access :')

**Pull request merged**
