### PR TITLE
Fix hover, click interaction with issue cards

### LINKED ISSUE #171: Issue cards on dashboard are not longer interactable
**Describe the bug**
For each PR/issues listed in the dashboard, it is expected that clicking it will redirect the user to the related Github page. However, right now the hyperlink is no longer working.

**Expected** (when hovered over)
image

**Current** (when hovered over)
image

### PR DESCRIPTION
**Pull request by chia-yh**
### Summary:

Fixes #171 

Issue cards are no longer interactable on the issue dashboard. After investigating, the cause is likely due to the implementation of scroll shadows in #148 , specifically manipulating the `z-index` in order to allow the shadow to be cast over the issue cards.

This PR changes the implementation of the scroll shadows in the issue dashboard to avoid manipulating the `z-index` of the issue cards, instead using pseudo-elements in `scrollable-container` and in a wrapper.

#### Type of change:

- 🐛 Bug Fix

### Changes Made:

- Remove specification of `z-index` in `issue-pr-cards`
- Remove `background` properties in `scrollable-container`
- Add pseudo-elements `::before` and `::after` to `scrollable-container` for scroll shadow covers
- Add `scrollable-container-wrapper`, with `::before` and `::after` pseudo-elements for scroll shadows

### Screenshots:

scroll_shadows_with_hover

### Proposed Commit Message:

```
Fix hover, click interaction with issue cards

Issue cards are no longer interactable as a result of the scroll shadow
implementation, likely due to specifing the z-index of issue cards.

Let's fix the interactions with issue cards so that users can hover and
click on them by modifying the implementation of scroll shadows.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [ ] I have tested my changes thoroughly.
- [ ] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [ ] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

**Review by Eclipse-Dominator — APPROVED** [review]
LGTM!

**Review by gycgabriel — CHANGES_REQUESTED** [review]
Fixed the links bug, but this bug shows the shadow even though there's nothing to scroll

image

I coloured the linear gradients to show what's going on:
image

**Comment by chia-yh** [comment]
> Fixed the links bug, but this bug shows the shadow even though there's nothing to scroll
> 
> image
> I coloured the linear gradients to show what's going on: image

Thanks for bringing this to my attention, I didn't consider the case where there weren't enough issues to hide cards below; I've resolved it in the latest commits by using `position: sticky`, and managed to remove the additional element for covering scroll shadows when no issues are present as its no longer necessary. The implementation should be a bit less messy with just pseudo elements for the `scrollable-container` and the wrapper.

**Review by gycgabriel — APPROVED** [review]
LGTM

**Pull request merged**
