### PR TITLE
Detailed view page

### LINKED ISSUE #69: Detailed dashboard view of individual users.
**Is your feature request related to a problem? Please describe.**
Sometimes, we might want to have a detailed view of contributions per user the user can click on a specific contributor of a repository to access a detailed report view of what he or she has done in the past. It is also a nice place to build other ways to view user contribution to a project (i.e. calendar view etc.) We can create individual modules for each different view and have a dashboard-like page for each user accessible via clicking on the username in the WATcher home screen. This also give us the flexibi

**Describe the solution you'd like**
Create specific page to view details of an individual similar to the Github profile page and populate it with information on the user related to the current repository as well as other statistics. 
image

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
### Summary:
Resolves #69

You can access this page by clicking on the Github usernames in the dashboard

### Changes Made:
Due to the the profile page resuing similar elements from other pages, large amount of components and code are being abstracted and modularised into individual components to avoid excess code duplication. A side effect of doing so is the improvement of readability of the components affected by the modularisation.

- Modularizes Filter bar into its own components
- Moves labelfilterbar to a component within the abstracted out filterbar
- Abstract out `dropdownfilter` into its own class
- Abstract out interfaces for `filterableSource` and `filterableComponents` for better code quality
- Modularizes profile page for ease of reading and future edits
- Adds a custom data source implementation to take in a custom issue source instead of the whole issue array for more efficiency
- Further abstract out filter functionalities to reduce code duplication
- Implements a basic profile page showing Issues and PRs related to the user
- Adds routing to the profile page
- Enables users to be access profile page via clicking on their profile
- Adds filterbar to the profile page
- Adds a summary stats mini component for the profile page
- Adds graphql queries to query for commits by the user
- Adds RSQ data structures to enable fast RSQ queries
- Adds a commit list to display commits by user
- Adds diffstats component to display line additions and deletions
- Adds ability to check cumulative stats across multiple commits
- Adds a refresh button to manually refresh commits
- Standardise all date time in profile page to follow DD/MM/YYYY h:mm:ss a
- Adds @angular/material-moment-adapter to support moment.js time on datepicker

### Sample Screenshot of UI

Profile page
image

Commit List
image

The various components
image

How commits are being handled within the page
image

#### DetailedViewerComponent
Responsible for structuring the page as well as passing data between components.
Also responsible for retrieving Issues and PRs from the repos and classifying them into "Created" and "Assigned" PRs and Issues to be displayed by the 4 ProfileListComponents

#### ProfileSummaryComponent
Sole purpose of displaying summary statistics generated by ProfileDetailsComponent

#### ProfileIconComponent
Displays the username and the github profile icon

#### DiffStatComponent
Visually displays the number of additions of lines and deletions of lines along with it's corresponding ratio

#### CommitList
Takes in a sorted list of commits and visually display each commit using a expansion panel. This component will also allow the user to select the range of commits to view by letting them select the start and end date.
A DiffStat component is used to summary the cumulative addition as well as deletion of commits in the current view

#### ProfileDetailsComponent
Calls upon the githubService to retrieve all commits made by the user in the specified repository. This component also passes the commit list to the CommitListComponent as well as generate the summary statistics which is to be displayed by the ProfileSummaryComponent

#### ProfileListComponent
Similar component to the CardViews in the main dashboard but it takes in an observable source instead of the users to filter.

#### FilterBarComponent
Abstracted out filter bar from main dashboard to avoid code duplications

### Notes
In the graphql types auto generated by codegen.yml, it is unable to generate the `history` type which leads to the inclusion of `//@ts-ignore` here in `GithubService`
```typescript
fetchCommitGraphqlByUser(userId: string): Observable<any> {
    // return newQueryRef.valueChanges;
    return this.fetchGraphqlList<FetchAllActivitiesFromUserQuery, any>(
      FetchAllActivitiesFromUser,
      {
        owner: ORG_NAME,
        name: REPO,
        id: userId
      },
      // @ts-ignore
      (result) => result.data.repository.defaultBranchRef.target.history.edges,
      GithubGraphqlCommitStat
    );
  }
```
---
There is a date select tag build in Angular Material that enables the users to select a range of queries (seen [here](https://material.angular.io/components/datepicker/overview#date-range-selection), This feature is only available after Angular Material v10 which means we do not have access to it right now. 
image

Thus, for the range select dialog, it might not be very appealing (although functional) as there is a much better alternative after upgrading to v10 angular material. As the current PR is already very massive, let's leave fixing the look and feel of the date range picker to another PR. 

---

The behavior when the user switch repo in the profile page is as follows:
1. Check if the current user exist in the new repo
2. If it does, no redirection occurs and data is being loaded into the current page,
3. If it does not, the page will be redirected to the dashboard

---

The lack of loading spinners in the profile page when a repo change occurs is related to a separate issue #124 and #100. 

### Commit Message:
```
There is a currently no way for the users to check the details of each user in a repository,
a detailed dashboard view for users to checkout summaries and recent activities can be useful.

Let's add a detailed dashboard view for each user while avoiding excessive code duplications
- Modularizes Filter bar into its own components
- Moves labelfilterbar to a component within the abstracted out filterbar
- Abstract out `dropdownfilter` into its own class
- Abstract out interfaces for `filterableSource` and `filterableComponents` for better code quality
- Modularizes profile page for ease of reading and future edits
- Adds a custom data source implementation to take in a custom issue source instead of the whole issue array for more efficiency
- Further abstract out filter functionalities to reduce code duplication
- Implements a basic profile page showing Issues and PRs related to the user
- Adds routing to the profile page
- Enables users to be access profile page via clicking on their profile
- Adds filterbar to the profile page
- Adds a summary stats mini component for the profile page
- Adds graphql queries to query for commits by the user
- Adds RSQ data structures to enable fast RSQ queries
- Adds a commit list to display commits by user
- Adds diffstats component to display line additions and deletions
- Adds ability to check cumulative stats across multiple commits
- Adds a refresh button to manually refresh commits
- Adds ability to filter commits using date ranges
- Adds ability to toggle the order commits are being displayed
- Standardise all date time in profile page to follow DD/MM/YYYY h:mm:ss a
- Adds @angular/material-moment-adapter to support moment.js time on datepicker

```

### CODE REVIEW

**Comment by Eclipse-Dominator** [comment]
Update 1.1:
- `CommitList` now shows the currently selected date range
- A sort button have been included to show commit from earliest to last
- Fixes bugs related to when user manually enter a date that is out of range
- Fixes profile list icon not centralized

image
image

**Comment by kkangs0226** [comment]
Thanks for making this PR, this will definitely improve WATcher. 

I do think this PR is making too many changes at once, it would be better if we could break it down into smaller PRs and merge them in one by one. 
E.g. 
1 PR - Modularization & abstraction of Filter-related components 
1 PR - Implementation of basic view page 
1 PR - Adding summary statistics / other features 
1 PR - standardisation of time 
and so on. 

This would make PR reviews easier & also make sure we can identify the source if there are any regressions in our application.

**Comment by Eclipse-Dominator** [comment]
> Thanks for making this PR, this will definitely improve WATcher.
> 
> I do think this PR is making too many changes at once, it would be better if we could break it down into smaller PRs and merge them in one by one. E.g. 1 PR - Modularization & abstraction of Filter-related components 1 PR - Implementation of basic view page 1 PR - Adding summary statistics / other features 1 PR - standardisation of time and so on.
> 
> This would make PR reviews easier & also make sure we can identify the source if there are any regressions in our application.

Alright I have split the PR into multiple smaller PRs!

**Comment by damithc** [comment]
@Eclipse-Dominator Also, consider the user POV, as I mentioned earlier today. 
Start with the high-level purpose of this page (e.g., see the total contribution of a team member?), and collect user stories/needs that are associated with that purpose. Then design the page to match those user stories (no more, no less).
Otherwise this page will end up having data that are not useful to the user and missing data that could be useful to the user.

**Pull request closed without merging**
