### PR TITLE
Support private repos

### LINKED ISSUE #6: Support private repositories
**Is your feature request related to a problem? Please describe.**
For WATcher to support NUS modules that use private repositories

**Describe the solution you'd like**
WATcher can work with private repositories

Change 'public_repo' permission parameter that is used in GithubService when fetching data.

### PR DESCRIPTION
**Pull request by joyngjr**
### Summary:

Fixes #6 

Previously, WATcher only populates the issues/PRs of public repos. 

#### Type of change:

- ✨ Enhancement

### Changes Made:

- Change github repo permission to support private repos

### Proposed Commit Message:

```
Add support for private repos.

Let's allow users to use WATcher for their private repositories.
```

<details><summary>
<h3>Checklist:</h3>
</summary>

- [ ] I have tested my changes thoroughly.
- [X] I have created tests for any new code files created in this PR or provided a link to a issue/PR that addresses this.
- [X] I have added or modified code comments to improve code readability where necessary.
- [ ] I have updated the project's documentation as necessary.

</details>

### CODE REVIEW

**Review by Eclipse-Dominator — APPROVED** [review]
LGTM!
It's also possible to explore the use of `repo:status` permission instead of `repo` which might be more secure but it's possible we might have functionality to reassign users in the future so let's leave it as it is.

**Comment by damithc** [comment]
Would this change cause potential users hesitate to use WATcher, because WATcher requires a more intrusive level of access to user repos? 🤔

**Comment by chunweii** [comment]
> Would this change cause potential users hesitate to use WATcher, because WATcher requires a more intrusive level of access to user repos? 🤔

Perhaps it would be better to allow the user to choose the permission level for WATcher when logging in?

**Comment by damithc** [comment]
> Perhaps it would be better to allow the user to choose the permission level for WATcher when logging in?

Yes, that might be better. But there will be complications such as the need to change the permission level later.

**Pull request merged**
