### PR TITLE
Autofill repository URL with Browser Cache

### LINKED ISSUE #30: Autofill repository URL with Browser Cache
**Is your feature request related to a problem? Please describe.**
It'll be nice to have repository URL autofilled and suggestions when the user accesses WATcher again. 

**Describe the solution you'd like**
Show repository URL autofill suggestions.

### PR DESCRIPTION
**Pull request by chia-yh**
### Summary:

Resolves #30 
Update WATcher to show repository URL autofill suggestions when entering repository location.

autofill_suggestion

### Changes Made:

-`session-selection.component.html`: added `mat-autocomplete` to handle autofill suggestions
-`session-selection.component.ts`: modify `initRepoForm()` to retrieve suggestions from `localStorage` and set up filter, `setupSession()` to update suggestions in `localStorage`
-`repo-change-form.component.html`: added `mat-autocomplete` to handle autofill suggestions
-`repo-change-form.component.ts`: add `initRepoChangeForm()` to retrieve suggestions from `localStorage` and set up filter

### Commit Message:

```
Add autofill for repository URL with browser cache

Adding autofill suggestions for repository location would improve the
user experience when accessing WATcher again.

Let's add repository URL autofill suggestions with the browser cache.
```

### CODE REVIEW

**Comment by chia-yh** [comment]
Something to consider in relation to this feature, should a similar autofill suggestion be applied to the dialog brought up by `openChangeRepoDialog`? Or should it utilise the `otherRepos` array when logged in, to provide repo suggestions as suggested in the `//TODO feature` under `phase.service.ts`?

**Comment by gycgabriel** [comment]
> Or should it utilise the `otherRepos` array when logged in, to provide repo suggestions as suggested in the `//TODO feature` under `phase.service.ts`?

The otherRepos array was actually intended for future features/phases that may use multiple repositories or a config repository. Example: Comparing two repositories. 

We should store them together - repo entered in change repo should be available for auto fill on front page also

**Comment by chia-yh** [comment]
> > Or should it utilise the `otherRepos` array when logged in, to provide repo suggestions as suggested in the `//TODO feature` under `phase.service.ts`?
> 
> 
> 
> The otherRepos array was actually intended for future features/phases that may use multiple repositories or a config repository. Example: Comparing two repositories. 
> 
> 
> 
> We should store them together - repo entered in change repo should be available for auto fill on front page also

Got it, I think that's how it's implemented at the moment.

Should the same autofill suggestions based on local storage also be available in the dialog brought up when changing repositories while logged in?

**Review by gycgabriel — COMMENTED** [review]
Had a brief look, looks good. Will check and test again

**Comment by gycgabriel** [comment]
> > > Or should it utilise the `otherRepos` array when logged in, to provide repo suggestions as suggested in the `//TODO feature` under `phase.service.ts`?
> > 
> > 
> > The otherRepos array was actually intended for future features/phases that may use multiple repositories or a config repository. Example: Comparing two repositories.
> > We should store them together - repo entered in change repo should be available for auto fill on front page also
> 
> Got it, I think that's how it's implemented at the moment.
> 
> Should the same autofill suggestions based on local storage also be available in the dialog brought up when changing repositories while logged in?

Yes that would be ideal

**Review by gycgabriel — APPROVED** [review]
LGTM

**Pull request merged**
